#!/bin/bash

#Explain: returns human formated string for seconds.
hdoc=$(cat <<EOT
  elapsed_time sec         returns formated time since sec (tics)
  elapsed_time sec -       returns formated sec
  elapsed_time sec1 sec2   returns formated difference
EOT
)

if [ -z $1 ]  ; then 
	echo -e "Usage: \n$hdoc\n"
	exit 1
fi

t1=$1

if [ -z $2 ]; then t2=$(date +"%s") ; #now
elif [ "$2" == '-' ] ; then t2=$1;t1=0; 
else t2=$2
fi

if [ $t1 -gt $t2 ] ; then
	t=$t1;
	t1=$t2
	t2=$t
fi

diff=$(( $t2 - $t1 ))
#echo "Diff: $diff"
daysec=$(( 60 * 60 *24 ))
hrsec=$(( 60 * 60 ))


mod=$(($diff % $daysec )) 
left=$(($diff - $mod ))
DAYS=$(( $left / $daysec ))
left=$(( $diff - $DAYS*$daysec ))

out=$(date -u -r $left +"%H:%M:%S h:m:s")


if [[ "$DAYS" -gt 0 ]] ; then 
out="$DAYS days, $out"
fi

out+=$hms
echo "$out"
exit 0
